#!/bin/bash

set -e

# set Timezone
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# set up php.ini file
if [ -z "$DEVELOPMENT_MODE" ]; then
  echo "USE PRODUCTION PHP.INI FILE"
  cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini  
else
  echo "USE DEVELOPMENT PHP.INI FILE"
  cp $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini
fi

#if env LISTEN_SOCKET is not empty - set socket listener
if [ -n "$LISTEN_SOCKET" ]; then
    sed -i -e "/^listen/d" $zz_docker_conf \
		&& echo "listen = $SOCKET_PATH" >> $zz_docker_conf \
		&& echo "user = www-data" >> $zz_docker_conf \
    && echo "group = www-data" >> $zz_docker_conf \
		&& echo "listen.mode = 0660" >> $zz_docker_conf \
    && echo "listen.owner = www-data" >> $zz_docker_conf \
    && echo "listen.group = www-data" >> $zz_docker_conf
fi
# invoke parent entrypoint
exec docker-php-entrypoint "$@"